package dev.archunitjava.model;

public enum DeclarationDependencySourceKind {
    ANNOTATION_DEFAULT_VALUE,
    ANNOTATION_TYPE,
    ANNOTATION_VALUE,
    CLASS_GENERIC_SIGNATURE,
    FIELD_DESCRIPTOR,
    FIELD_GENERIC_SIGNATURE,
    INTERFACE,
    METHOD_GENERIC_SIGNATURE,
    METHOD_PARAMETER_DESCRIPTOR,
    METHOD_RETURN_DESCRIPTOR,
    PERMITTED_SUBCLASS,
    RECORD_COMPONENT_DESCRIPTOR,
    RECORD_COMPONENT_GENERIC_SIGNATURE,
    SUPERCLASS
}
