package dev.archunitjava.model;

public enum NestingDiagnosticCode {
    CONFLICTING_ENCLOSING_METHOD_EVIDENCE,
    CONFLICTING_INNER_CLASS_EVIDENCE,
    CONFLICTING_LEXICAL_OWNER_EVIDENCE,
    CONFLICTING_NEST_HOST_EVIDENCE,
    DUPLICATE_NEST_MEMBER,
    INCOMPLETE_LEXICAL_EVIDENCE,
    NEST_HOST_AND_MEMBERS_DECLARED,
    SELF_NEST_HOST
}
