package dev.archunitjava.model;

public enum SealedHierarchyDiagnosticCode {
    DUPLICATE_PERMITTED_SUBCLASS,
    EMPTY_PERMITTED_SUBCLASS_LIST,
    MISSING_PERMITTED_SUBCLASS,
    OBSERVED_SUBCLASS_NOT_PERMITTED,
    PERMITTED_RELATIONSHIP_UNKNOWN,
    PERMITTED_SUBCLASS_NOT_DIRECT,
    QUERY_TYPE_MISSING,
    SELF_PERMITTED_SUBCLASS
}
